wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709892260.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.8
      5: 0.16.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
