program: src/train.py
method: random  # Options: grid, random, bayes
metric:
  name: val_loss
  goal: minimize
project: "Threshold GPT No Contamination"        # Specify your W&B project name
entity: "thomasevers9"          # Specify your W&B username or team name
parameters:
  batch_size:
    # values: [1024]             # 4 * 16384 = 65536
    values: [64]               # 4 * 8192 = 32768
  limit_train_batches:
    values: [64]
  max_iters:
    values: [1400]
  lr:
    values: [1e-4, 5e-4]
  block_size:
    values: [128, 256]
  n_embd:
    values: [512, 1024]
  n_head:
    values: [16]
  n_layer:
    values: [6, 12, 18]
  dropout:
    values: [0, 0.4]
  token:
    values: ["openai"]
  precision:
    values: ["16-mixed"]         # Can add "16" if BPE is fixed
  eval_interval:
    values: [5]
  limit_val_batches:
    values: [128]
  min_delta_lr_factor:
    values: [20]
  T_threshold:
    values: [0, 0.025]
